#!/usr/bin/env bash

set -eo pipefail

if [[ -f /etc/environment_proxy ]]; then
  source /etc/environment_proxy
fi

parse_yaml() {
  local prefix=$2
  local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
  sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
  awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
        vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
        printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
  }'
}

export HOME=/app
mkdir -p $HOME

cd $HOME

## Load profile.d and release config

shopt -s nullglob
mkdir -p .profile.d

for file in .profile.d/*; do
  source $file
done
hash -r

## Inject "start" command to run processes defined in Procfile
case "$1" in
  start)
    eval $(parse_yaml Procfile "config_")
    processType=$(echo config_$2)
    command=${!processType}
    ;;

  *)
    command="$@"
    ;;
esac

## Run!
exec bash -c "$command"
